"""empty message

Revision ID: 0dc3f89d4be8
Revises: f31c665dd1ec
Create Date: 2023-07-18 22:49:27.766195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dc3f89d4be8'
down_revision = 'f31c665dd1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_3', type_='foreignkey')
        batch_op.drop_column('product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_item_ibfk_3', 'product', ['product'], ['id'])

    # ### end Alembic commands ###
