"""empty message

Revision ID: 7ea3ecfc4a56
Revises: aa9d8bf3edd8
Create Date: 2023-07-17 02:46:30.349018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ea3ecfc4a56'
down_revision = 'aa9d8bf3edd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('order_item_ibfk_2', type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('order_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_item_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_item_ibfk_2', 'order_item', ['order_item_id'], ['id'])
        batch_op.create_foreign_key('order_item_ibfk_1', 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
