"""empty message

Revision ID: a6e9fe32f278
Revises: 0dc3f89d4be8
Create Date: 2023-07-18 23:45:01.636918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e9fe32f278'
down_revision = '0dc3f89d4be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product')

    # ### end Alembic commands ###
