"""empty message

Revision ID: f31c665dd1ec
Revises: 80eea22bf4f9
Create Date: 2023-07-17 16:13:20.897207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31c665dd1ec'
down_revision = '80eea22bf4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product')

    # ### end Alembic commands ###
